CREATE DATABASE SCALER;
USE SCALER;
CREATE TABLE STUDENT
(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME VARCHAR(50) DEFAULT 'NOT AVAILABLE' NOT NULL,
    LASTNAME NVARCHAR(50) NOT NULL,
    EMAIL NVARCHAR(50) NOT NULL,
    DOB DATE NOT NULL,
    ENROLLMENTDATE TIMESTAMP,
    PSP DECIMAL(3,2),
    BATCHID INT NOT NULL,
    ISACTIVE BOOLEAN NOT NULL,
    TOPPER BIT
);
DELETE FROM STUDENT WHERE ID = 1;
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, EMAIL, DOB, ENROLLMENTDATE, PSP, BATCHID, ISACTIVE, TOPPER)
			VALUES ('MAHESH', 'SINGH','MEET2MAHESH17@GMAIL.COM','1999-05-07',NOW(), 9.8, 5, TRUE, 1);
SELECT * FROM STUDENT;

ALTER TABLE STUDENT MODIFY EMAIL NVARCHAR(50) UNIQUE;